update=3/19/2020 1:50:29 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../../../KiCad Library/SparkFun-KiCad-Libraries-master;../../../../KiCad Library/digikey-kicad-library-master;../../../../KiCad Library/arduino nano290313
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/1w1700
LibName31=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/4n35_opto
LibName32=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/5V_buck
LibName33=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/24MHz
LibName34=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/74hc32
LibName35=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/0850bm14e0016
LibName36=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/2450BM14G0011
LibName37=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/18650-lipobattery
LibName38=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/adg733
LibName39=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/AMS1117-3V3
LibName40=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/antenna_2.4GHz
LibName41=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cc1310_7x7
LibName42=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cc1310_7x7_new
LibName43=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cc2650
LibName44=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cc2650_7x7
LibName45=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cdd-11n
LibName46=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cnt-rj45_10pin
LibName47=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/connectors
LibName48=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/cp2102
LibName49=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/crystal_24MHz
LibName50=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/crystal-new
LibName51=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/dd04cvsa-5_6_9_12v
LibName52=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/df08s1_bridge_rec-ic
LibName53=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/dm3at-sf-pej
LibName54=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/edge_sma
LibName55=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/esp-12e
LibName56=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/esp-32_wroom32_Exact
LibName57=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/esp-32_wroom32_rectangle
LibName58=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/fabdetails
LibName59=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/henlv_5v_2a
LibName60=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/henlv-ac220s3_3dcs-3w
LibName61=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/henlv-ac220s5dcs-3w
LibName62=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/HL6528-G
LibName63=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/hlw8012
LibName64=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/HM-10
LibName65=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/ic-cpu
LibName66=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/ic-io
LibName67=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/ic-misc
LibName68=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/ic-power
LibName69=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/inductor
LibName70=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/inductor_L
LibName71=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/JTAG
LibName72=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/L293DNE
LibName73=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/L293N
LibName74=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/lcd16x2_i2c
LibName75=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/logo
LibName76=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/lp5907_ldo_250ma
LibName77=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/ltr-303als
LibName78=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/mff2_embeded_sim
LibName79=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/mic29302
LibName80=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/mic35302
LibName81=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/Micro_USB_B
LibName82=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/mountinghole
LibName83=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/nlas5223
LibName84=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/opto
LibName85=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/opto-other
LibName86=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/passive
LibName87=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/power
LibName88=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/PROBE
LibName89=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/prtr5v0u2x
LibName90=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/rfid_reader
LibName91=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/RFM_module
LibName92=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/samd20e18-au
LibName93=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/samd20gxxa-au
LibName94=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/samd21gxxa-au
LibName95=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/saml21gxxb-mu
LibName96=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/sfm-110-02-s-d-a-k-tr
LibName97=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/si7006
LibName98=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/sim_holder
LibName99=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/SIM800C
LibName100=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/simcardholder_shield
LibName101=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/simcom
LibName102=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/smf05c
LibName103=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/Songle_SRD-03VDC-SL-C
LibName104=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/sw_push_small_h
LibName105=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/switch_dpdt
LibName106=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/switch_spdt
LibName107=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/switches
LibName108=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/touchpad_single
LibName109=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/tps782
LibName110=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/TPS61021A
LibName111=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/tps63051
LibName112=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/TPS562201
LibName113=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/triac_board
LibName114=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/ttp224n-bsb
LibName115=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/txb0108
LibName116=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/usb_a_4_pins
LibName117=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/usb_a_male_pcb
LibName118=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/vbus053az
LibName119=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/via
LibName120=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/kicad-library-master/library/xbee
LibName121=C:/Users/adahal/Desktop/AJ/KiCad/1599 tester/arduino-kicad-library-master/arduino-kicad-library-master/arduino
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=45-1599-1 PCB_voltage_divider.net
PadDrill=1.016
PadDrillOvalY=1.016
PadSizeH=1.8796
PadSizeV=1.8796
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.005906
BoardOutlineThickness=0.005906
ModuleOutlineThickness=0.15
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
