update=2/28/2020 1:26:09 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=ni_daq
LibName31=relays
LibName32=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Addressable-Specialty
LibName33=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName34=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Automotive-Relays
LibName35=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Balun
LibName36=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Barrel-Audio-Connectors
LibName37=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName38=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName39=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName40=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName41=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Coaxial-Connectors-RF
LibName42=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Current-Transducers
LibName43=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName44=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName45=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName46=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName47=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName48=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_DC-DC-Converters
LibName49=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Digital-Isolators
LibName50=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName51=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName52=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName53=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Zener-Single
LibName54=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName55=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_D-Sub-Connectors
LibName56=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Embedded-Microcontrollers
LibName57=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Encoders
LibName58=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName59=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName60=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Fixed-Inductors
LibName61=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Fuses
LibName62=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Gas-Sensors
LibName63=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName64=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Image-Sensors-Camera
LibName65=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName66=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName67=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName68=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName69=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Controllers
LibName70=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName71=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-I-O-Expanders
LibName72=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Modules
LibName73=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName74=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName75=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Interface-Specialized
LibName76=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_LED-Indication-Discrete
LibName77=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName78=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName79=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName80=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Linear-Comparators
LibName81=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName82=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Flip-Flops
LibName83=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName84=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Multivibrators
LibName85=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Shift-Registers
LibName86=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName87=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName88=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName89=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName90=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName91=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Memory
LibName92=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName93=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Microphones
LibName94=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks
LibName95=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName96=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName97=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName98=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName99=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Navigation-Switches-Joystick
LibName100=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName101=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName102=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName103=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName104=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName105=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Logic-Output
LibName106=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName107=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName108=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Oscillators
LibName109=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName110=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Chargers
LibName111=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Management
LibName112=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName113=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName114=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Gate-Drivers
LibName115=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-LED-Drivers
LibName116=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName117=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName118=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName119=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName120=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName121=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Supervisors
LibName122=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Thermal-Management
LibName123=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName124=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Reference
LibName125=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName126=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName127=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName128=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName129=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName130=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName131=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Programmable-Oscillators
LibName132=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Pushbutton-Switches
LibName133=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName134=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Reed-Relays
LibName135=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Resistor-Networks-Arrays
LibName136=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Amplifiers
LibName137=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Antennas
LibName138=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Demodulators
LibName139=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Detectors
LibName140=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName141=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName142=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Receivers
LibName143=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Switches
LibName144=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-ICs
LibName145=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-Modules
LibName146=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_RF-Transmitters
LibName147=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName148=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName149=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName150=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Slide-Switches
LibName151=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Solid-State-Relays
LibName152=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Specialized-ICs
LibName153=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Specialized-Sensors
LibName154=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Surge-Suppression-ICs
LibName155=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Tactile-Switches
LibName156=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName157=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName158=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName159=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-SCRs
LibName160=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-TRIACs
LibName161=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Toggle-Switches
LibName162=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName163=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName164=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName165=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName166=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName167=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName168=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName169=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Transistors-JFETs
LibName170=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_Trimmer-Potentiometers
LibName171=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_TVS-Diodes
LibName172=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_TVS-Mixed-Technology
LibName173=C:/Users/zdigennaro/Documents/KiCad Library/digikey-kicad-library-master/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName174=C:/Users/zdigennaro/Documents/Test Fixture Projects/QCD System/232-336-1 Assembly/232-336-1 B1/Relay_EC2_5NU
LibName175=Arduino_Uno_R3_From_Scratch
LibName176=C:/Users/zdigennaro/Documents/KiCad Library/KiCAD/symbols
LibName177=45-1569-1 J3
LibName178=74xgxx
LibName179=ac-dc
LibName180=actel
LibName181=allegro
LibName182=Altera
LibName183=analog_devices
LibName184=arduino_nano
LibName185=battery_management
LibName186=bbd
LibName187=bosch
LibName188=brooktre
LibName189=cmos_ieee
LibName190=Connector-Custom
LibName191=dc-dc
LibName192=diode
LibName193=elec-unifil
LibName194=ESD_Protection
LibName195=ftdi
LibName196=gennum
LibName197=graphic
LibName198=hc11
LibName199=ir
LibName200=Lattice
LibName201=leds
LibName202=logo
LibName203=maxim
LibName204=mechanical
LibName205=microchip_dspic33dsc
LibName206=microchip_pic10mcu
LibName207=microchip_pic12mcu
LibName208=microchip_pic16mcu
LibName209=microchip_pic18mcu
LibName210=microchip_pic24mcu
LibName211=microchip_pic32mcu
LibName212=modules
LibName213=motor_drivers
LibName214=motors
LibName215=msp430
LibName216=NHD-0216CW-AW3
LibName217=nordicsemi
LibName218=nxp
LibName219=nxp_armmcu
LibName220=onsemi
LibName221=Oscillators
LibName222=Power_Management
LibName223=powerint
LibName224=pspice
LibName225=references
LibName226=rfcom
LibName227=RPi_Zero_pHat_Template-cache
LibName228=sensors
LibName229=shield_arduino
LibName230=silabs
LibName231=SparkFun-Aesthetics
LibName232=SparkFun-Batteries
LibName233=SparkFun-Boards
LibName234=SparkFun-Capacitors
LibName235=SparkFun-Clocks
LibName236=SparkFun-Coils
LibName237=SparkFun-Connectors
LibName238=SparkFun-DiscreteSemi
LibName239=SparkFun-Displays
LibName240=SparkFun-Electromechanical
LibName241=SparkFun-Fuses
LibName242=SparkFun-GPS
LibName243=SparkFun-Hardware
LibName244=SparkFun-IC-Amplifiers
LibName245=SparkFun-IC-Comms
LibName246=SparkFun-IC-Conversion
LibName247=SparkFun-IC-Logic
LibName248=SparkFun-IC-Memory
LibName249=SparkFun-IC-Microcontroller
LibName250=SparkFun-IC-Power
LibName251=SparkFun-IC-Special-Function
LibName252=SparkFun-Jumpers
LibName253=SparkFun-LED
LibName254=SparkFun-PowerSymbols
LibName255=SparkFun-Resistors
LibName256=SparkFun-RF
LibName257=SparkFun-Sensors
LibName258=SparkFun-Switches
LibName259=stm8
LibName260=stm32
LibName261=supertex
LibName262=switches
LibName263=symbols
LibName264=transf
LibName265=triac_thyristor
LibName266=ttl_ieee
LibName267=video
LibName268=wiznet
LibName269=Worldsemi
LibName270=Xicor
LibName271=zetex
LibName272=Zilog
LibName273=Relay_EC2_5NU
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=45-1523-1_New_AJ.net
PadDrill=3.175
PadDrillOvalY=3.175
PadSizeH=3.175
PadSizeV=3.175
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.09999999999999999
ModuleOutlineThickness=0.15
